/* generated by build.js — do not edit */
const VERSION = "f04039cb";
const CACHE = 'blendmandu-' + VERSION;
const PRECACHE = [
  "/assets/css/style.css?v=f04039cb",
  "/assets/js/app.js?v=f04039cb",
  "/assets/js/products.js?v=f04039cb",
  "/assets/js/i18n.js?v=f04039cb",
  "/assets/js/analytics.js?v=f04039cb",
  "/assets/vendor/lenis.min.js",
  "/favicon.svg",
  "/icon-192.png",
  "/icon-512.png"
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(PRECACHE).catch(() => {}))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never touch fonts/analytics

  const isHTML = req.mode === 'navigate' ||
                 (req.headers.get('accept') || '').includes('text/html');

  if (isHTML) {
    // network-first: prices and the menu must never be served stale
    e.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then(r => r || caches.match('/index.html')))
    );
    return;
  }

  /* Cache-first is safe for hashed assets because the URL changes when the
     file does. But only store entries matching THIS build: a long-lived
     version otherwise accumulates every superseded ?v= asset forever. */
  const v = url.searchParams.get('v');
  const storable = !v || v === VERSION;

  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res.ok && storable) {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
