/* generated by build.js — do not edit */
const VERSION = "d5e2adc8";
const CACHE = 'blendmandu-' + VERSION;
const PRECACHE = [
  "/assets/css/style.css?v=d5e2adc8",
  "/assets/js/app.js?v=d5e2adc8",
  "/assets/js/products.js?v=d5e2adc8",
  "/assets/js/i18n.js?v=d5e2adc8",
  "/assets/js/analytics.js?v=d5e2adc8",
  "/assets/vendor/lenis.min.js",
  "/favicon.svg",
  "/icon-192.png",
  "/icon-512.png",
  "/index.html",
  "/ne/index.html"
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(PRECACHE).catch(() => {}))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never touch fonts/analytics

  const isHTML = req.mode === 'navigate' ||
                 (req.headers.get('accept') || '').includes('text/html');

  if (isHTML) {
    // network-first: prices and the menu must never be served stale
    e.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(async () => {
          const hit = await caches.match(req);
          if (hit) return hit;
          // fall back to the shell for the language the visitor is in
          const shell = new URL(req.url).pathname.startsWith('/ne/')
            ? '/ne/index.html' : '/index.html';
          return (await caches.match(shell)) ||
            new Response('<h1>Offline</h1><p>Reconnect and reload.</p>',
              { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        })
    );
    return;
  }

  /* Cache-first is safe for hashed assets because the URL changes when the
     file does. But only store entries matching THIS build: a long-lived
     version otherwise accumulates every superseded ?v= asset forever. */
  const v = url.searchParams.get('v');
  const storable = !v || v === VERSION;

  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res.ok && storable) {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => Response.error()))   // never settle respondWith with undefined
  );
});
